name: Contract Testing
on:
  push:
    branches:
      - dev 
      - main 
      - testcase-updates
jobs:
  js-test-cases:
    runs-on: ubuntu-latest
    steps:    
    - uses: actions/checkout@v1
    
    - name: Environment Setup
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
        
    - name: install flow cli
      run: sh -ci "$(curl -fsSL https://storage.googleapis.com/flow-cli/install.sh)"
    - name: check flow version
      run: flow version
      
    - name: install node_modules and run test_cases
      working-directory: ./test/js
      run: |
            pwd
            flow init
            npm i
            npm run test
